import {StyleSheet, Platform} from 'react-native';
//local import
import R from '../../../R';
import {horizontalScale} from '../../../../res/scale';
import {dimensions} from '../../../../res/dimensions';

export default StyleSheet.create({
  titleText: {
    fontFamily: R.fonts.primaryBold,
    fontWeight: 'bold',
    fontSize: 28,
    //paddingHorizontal: 5,
    paddingVertical: 10,
    color: '#ffffff',
    textAlign: 'left',
  },

  subText: {
    fontFamily: R.fonts.primaryRegular,
    fontWeight: '400',
    fontSize: 18,
    //paddingHorizontal: 5,

    color: '#ffffff',
    textAlign: 'left',
  },

  todaysSpendCardContainer: {
    backgroundColor: R.themes.boxBackgroundColour,
   
    borderRadius: 5,
    //alignItems: 'center',
    // padding: '5%',
  },
  cardContainer: {
    backgroundColor: R.themes.boxBackgroundColour,
    flexDirection: 'row',
    flex: 0.21,
    margin: '2%',
    borderRadius: R.dimensions.hp('2%'),
    alignItems: 'center',
    padding: '5%',
    marginHorizontal: '4%',
  },
  cardImage: {
    height: R.dimensions.wp('26%'),
    width: R.dimensions.wp('26%'),
    top: 20,
    left: 20,
  },
  coinImage: {
    width: R.dimensions.wp('8%'),
    height: R.dimensions.wp('8%'),
  },

  cardImageContainer: {
    position: 'absolute',
    right: '8%',
    top: -2,
    //bottom: '2%',
  },
  pointText: {
    fontFamily: R.fonts.primaryBold,
    marginHorizontal: '3%',
    fontSize: R.dimensions.hp('3%'),
    color: R.themes.backgroundColor,
    fontWeight: '900',
  },
  rewardContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: '5%',
  },
  couponBox: {
    padding: 15,
    borderRadius: R.dimensions.hp('5%'),
    borderWidth: 0.5,
    borderColor: R.colors.lightgrey,
    backgroundColor: R.themes.backgroundColor,
    width: R.dimensions.hp('38%'),
    margin: R.dimensions.hp('1.5%'),
    elevation: 6,
    borderRadius: 6,
    shadowOffset: {
      width: 2,
      height: 2,
    },
    shadowOpacity: 0.6,
  },
  flexBox: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    width: '100%',
  },
  alignRight: {
    //alignSelf: 'flex-end',
  },
  terms: {
    fontSize: R.dimensions.hp('1.5%'),
    fontFamily: R.fonts.primaryBold,
    color: R.colors.grey,
  },
  date: {
    fontSize: 11,
    fontFamily: R.fonts.primaryBond2,
    color: R.colors.black,
  },
  aldo: {
    color: R.colors.black,
    fontSize: R.dimensions.hp('2.2%'),
    fontFamily: R.fonts.primaryBold,
  },
  space: {
    marginTop: 20,
    paddingHorizontal: 15,
  },
  Vovcher: {
    fontSize: R.dimensions.hp('2%'),
    fontFamily: R.fonts.primaryBold,
  },
  coinBox: {
    borderRadius: R.dimensions.hp('3%'),
    backgroundColor: '#ddd',
    // width: R.dimensions.hp('8%'),
    alignSelf: 'flex-end',
    marginBottom: 5,
    flexDirection: 'row',
    justifyContent: 'space-around',
    padding: 6,
    alignItems: 'center',
  },
  filterBox: {
    borderRadius: R.dimensions.hp('2%'),
    backgroundColor: R.colors.lightCardGray,
    alignSelf: 'flex-end',
    marginBottom: 5,
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 15,
    paddingVertical: 6,
    alignItems: 'center',
  },
  trendcoinBox: {
    backgroundColor: 'transparent',
    padding: 0,
    width: R.dimensions.hp('10%'),
  },
  coinText: {
    paddingVertical: 1,

    alignSelf: 'center',
    color: R.colors.primaryBrand2,
    fontSize: 16,
    fontWeight: '700',
    fontFamily: R.fonts.primaryBrand2,
    paddingHorizontal: '3%',
  },
  coinTextExpire: {
    color: R.colors.grey,
    fontSize: 13,
    fontFamily: R.fonts.primaryBold,
    paddingHorizontal: '2%',
  },
  filterText: {
    color: R.colors.black,
    fontSize: 13,
    fontFamily: R.fonts.primaryBold,
    marginRight: 5,
  },
  flex: {
    display: 'flex',
    flexDirection: 'row',
  },
  CoinMoney: {
    width: 15,
    height: 15,
    resizeMode: 'contain',
    paddingVertical: 10,
  },

  LocationPin: {
    width: 16,
    height: 16,
    marginLeft: 3,
    alignSelf: 'flex-start',

    tintColor: R.colors.primaryBrand2,
  },
  CoinMoneySize: {
    width: 15,
    height: 15,
    // margin:2,
  },
  silvrText: {
    fontSize: 14,
    fontFamily: R.fonts.primaryBold,

    // marginBottom:10,
    // marginTop:20
  },
  heading: {
    paddingLeft: '4%',
    fontFamily: R.fonts.primaryBold,
    fontSize: R.dimensions.hp('2%'),
    color: R.themes.backgroundColor,
    // marginBottom:10,
    // marginTop:20
  },
  giftVovcher: {
    fontSize: 13,
    fontFamily: R.fonts.primaryRegular,
    // fontWeight:'bold',
  },
  mainContainer: {
    paddingBottom: '20%',
    // marginHorizontal: '3%',
  },
  border: {
    height: 1,
    width: 50,
    backgroundColor: R.themes.boxBackgroundColour,
    marginTop: 5,
    marginLeft: 8,
  },
  trendingBox: {
    borderWidth: 2,
    borderColor: R.colors.primaryBrand2,
    marginBottom: R.dimensions.hp('1.4%'),
    // marginHorizontal: R.dimensions.wp('2%'),
    marginLeft: R.dimensions.wp('3%'),
    marginRight: R.dimensions.wp('3%'),
    alignItems: 'center',
    borderRadius: 8,
  },
  cardStyle: {
    alignItems: 'center',
  },
  trendingBoxParent: {
    // paddingHorizontal: 10,
    borderRadius: R.dimensions.hp('1.4%'),
    borderWidth: 2,
    borderColor: R.colors.primaryBrand2,
    backgroundColor: R.themes.backgroundColor,
    marginVertical: R.dimensions.hp('1.4%'),
    alignItems: 'center',
  },
  headerImg: {
    position: 'relative',
    left: '20%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerIcon: {
    justifyContent: 'center',
    height: horizontalScale(6),
    width: horizontalScale(11),
    tintColor: R.themes.backgroundColor,
  },
  voucherLeftCount: {
    paddingHorizontal: '2%',
    paddingVertical: '0.6%',
    // marginTop: 3,
    flexDirection: 'row',
    borderRadius: 3,
    marginRight: '2%',
    backgroundColor: R.colors.primaryBrand2,
    alignItems: 'center',
    justifyContent: 'center',
  },
  voucherLeftCountText: {
    fontSize: 11,
    paddingVertical: 2,
    fontFamily: R.fonts.primaryRegular,
    color: R.themes.backgroundColor,
  },
  trendingBoxExpired: {
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderRadius: R.dimensions.hp('1%'),
    borderWidth: 1.5,
    borderColor: R.colors.grey,
    backgroundColor: R.themes.backgroundColor,
    // width: R.dimensions.hp('38%'),
    marginVertical: R.dimensions.hp('1.4%'),
    alignItems: 'center',
  },

  flexLeft: {
    flex: 1,

    // borderWidth:1
  },
  box: {
    height: R.dimensions.hp('2.6%'),
    width: R.dimensions.wp('26%'),
    marginLeft: '69%',
    // borderRadius: 5,
    //  marginVertical: 10,
    backgroundColor: R.colors.primaryBrand2,
    alignItems: 'center',
  },
  flexRight: {
    flex: 4,
    // borderWidth:1
  },
  lineHorizontal: {
    borderWidth: 0.5,
    borderColor: R.colors.orange,
    marginVertical: 5,
  },
  lineHorizontalExpired: {
    borderWidth: 0.5,
    borderColor: R.colors.grey,
    marginVertical: 5,
  },
  VovcherOrange: {
    color: R.colors.primaryBrand2,
  },
  VovcherGrey: {
    color: R.colors.grey,
  },
  alignCenter: {
    alignItems: 'center',
  },
  headingTitle: {
    paddingTop: 20,
    paddingBottom: 10,
  },
  logoImage: {
    height: 50,
    width: 50,
  },
  cardBox: {
    paddingHorizontal: 15,
    paddingVertical: 40,
    borderRadius: R.dimensions.hp('2%'),
    borderWidth: 1,
    borderColor: R.colors.lightgrey,
    backgroundColor: R.themes.backgroundColor,
    justifyContent: 'center',
  },
  progress: {
    marginVertical: 10,
  },
  ArrowUpDown: {
    height: 13,
    width: 13,
  },
  tabBox: {
    paddingTop: 30,
  },
  tabText: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomColor: R.themes.boxBackgroundColour,
    borderBottomWidth: 2,
  },
  tabTextInactive: {
    paddingHorizontal: 10,
    paddingVertical: 10,
    borderBottomColor: R.colors.lightgrey,
    borderBottomWidth: 1,
  },
  inActiveCard: {
    backgroundColor: R.colors.lightCardGray,
    height: 10,
    width: 10,
  },
  activeCard: {
    backgroundColor: '#FFE1AC',
    height: 10,
    width: 10,
  },
  select_CategoryView: {
    marginVertical: '5%',
    marginHorizontal: '3%',
    borderRadius: 10,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    padding: '5%',
  },

  select_CategoryText: {
    color: R.themes.backgroundColor,
    fontFamily: R.fonts.primaryBold,
    fontSize: R.dimensions.hp('2.1%'),
    fontWeight: '700',
    paddingVertical: R.dimensions.hp('2.1%'),
  },
  voucher_TextStyle: {
    fontWeight: '400',
    fontSize: R.dimensions.hp('1%'),
    textAlign: 'center',
    marginTop: 10,
    lineHeight: 9,
    color: R.themes.backgroundColor,
    fontFamily: R.fonts.primaryBold,
  },
  voucher_AfterTextStyle: {
    fontWeight: '700',
    fontSize: R.dimensions.hp('1%'),
    textAlign: 'center',
    marginTop: 10,
    lineHeight: 9,
    color: 'white',
    fontFamily: R.fonts.primaryBold,
  },
  voucher_ImageStyle: {
    width: R.dimensions.wp(10),
    height: R.dimensions.wp(10),
    // marginTop: R.dimensions.wp('4%'),
    tintColor: 'white',
    alignSelf: 'center',
    resizeMode: 'cover',
  },
  voucher_AfterImageStyle: {
    width: R.dimensions.wp(10),
    height: R.dimensions.wp(10),
    // marginTop: R.dimensions.wp('4%'),
    tintColor: 'white',
    alignSelf: 'center',
    resizeMode: 'contain',
  },
  voucher_TouchableView: {
    height: R.dimensions.hp('11%'),
    width: R.dimensions.wp('22%'),
    justifyContent: 'center',
    borderRadius: 8,
    alignSelf: 'center',
    backgroundColor: R.colors.purple,
    shadowOffset: {
      width: 0,
      height: 0,
    },
    shadowOpacity: 0.6,
    elevation: 6,
  },
  voucher_AfterTouchableView: {
    height: R.dimensions.hp('11%'),
    width: R.dimensions.wp('22%'),
    justifyContent: 'center',
    borderRadius: 8,
    alignSelf: 'center',
    backgroundColor: R.colors.purple,
    borderWidth: 1,
    borderColor: R.themes.boxBackgroundColour,
  },

  tabText: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomColor: 'white',
    borderBottomWidth: 2,
    width: 120,
  },
  tabTextInactive: {
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderBottomColor: R.colors.primaryBrand2,
    borderBottomWidth: 1,
  },
  heading: {
    lineHeight: 18,
    fontWeight: '700',
    paddingLeft: '4%',
    fontFamily: R.fonts.primaryBold,
    fontSize: R.dimensions.hp('2%'),
    color: R.themes.backgroundColor,
  },
  headinginactive: {
    paddingLeft: '4%',
    lineHeight: 18,
    fontWeight: '500',
    fontFamily: R.fonts.primaryBold,
    fontSize: R.dimensions.hp('2%'),
    color: R.colors.grey,
  },
  rewardcardmaskAll: {
    marginVertical: '3%',

    width: dimensions.wp(90),

    resizeMode: 'contain',
    alignSelf: 'center',
  },
  rewardcardmaskDaily: {
    width: R.dimensions.wp(90),
    height: R.dimensions.hp(35),
    resizeMode: 'contain',
    alignSelf: 'center',
    justifyContent: 'center',
  },
  yearlymask: {
    width: R.dimensions.wp(90),
    resizeMode: 'contain',
  },
  spendTitleAmtView: {
    backgroundColor: '#921C81',
    width: R.dimensions.wp(50),
    flexDirection: 'row',
  },
  spendTitleAmtViewlogo: {
    width: R.dimensions.wp(6),
    height: R.dimensions.wp(6),
    alignSelf: 'center',
    right: 10,

    position: 'absolute',
  },
  cardTitle: {
    fontSize: 16,
    fontFamily: R.fonts.primaryMedium,
    color: R.themes.backgroundColor,

    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0,
    marginLeft: '15%',
    textAlign: 'left',
    textAlignVertical: 'top',
  },
  SpecialcardTitle: {
    fontSize: 14,
    fontFamily: R.fonts.primaryMedium,
    color: R.themes.backgroundColor,
    lineHeight: 18,
    fontWeight: '700',
    letterSpacing: 0,
    marginLeft: '2%',
    textAlign: 'left',
    textAlignVertical: 'top',
    marginTop: '2%',
  },
  DailycardTitle: {
    fontSize: 16,
    fontFamily: R.fonts.primaryMedium,
    color: R.themes.backgroundColor,
    lineHeight: 20,
    fontWeight: '700',
    letterSpacing: 0,
  },

  cardTitleAmt: {
    fontSize: 20,
    fontFamily: R.fonts.primaryMedium,
    color: R.themes.backgroundColor,

    lineHeight: 20,
    fontWeight: '900',
    letterSpacing: 0,
    marginLeft: '15%',
    textAlign: 'left',
    textAlignVertical: 'top',
    marginTop: '2%',
  },
  DailycardTitleAmt: {
    fontSize: 22,
    fontFamily: R.fonts.primaryMedium,
    color: R.themes.backgroundColor,
    fontWeight: 'bold',
    letterSpacing: 0,
    marginTop: 10,
  },
  cardSubtitle: {
    fontSize: horizontalScale(10),
    fontFamily: R.fonts.primaryRegular,
    color: '#ffffff',
    //fontWeight: 'bold',
    letterSpacing: 0,
    lineHeight: 15,
    textAlign: 'left',
    width: '70%',
    flexWrap: 'wrap',
    textAlignVertical: 'top',
    marginTop: '2%',
    marginLeft: '2%',
  },
  cardSubtitleFooter: {
    fontSize: horizontalScale(12),
    fontFamily: R.fonts.primaryRegular,
    color: R.colors.primaryBrand2,
    fontWeight: '600',
    letterSpacing: 0,
    lineHeight: 15,
    textAlign: 'left',
    width: '100%',
    flexWrap: 'wrap',
  },
  montlyCardSubtitle: {
    fontSize: horizontalScale(8),
    fontFamily: R.fonts.primaryRegular,
    color: R.themes.backgroundColor,
    fontWeight: '700',
    letterSpacing: 0,
    textAlign: 'left',
  },
  progressbarvalue: {
    fontSize: horizontalScale(9),
    fontFamily: R.fonts.primaryBold,
    color: R.themes.backgroundColor,
    fontWeight: 'bold',
    letterSpacing: 0,
    alignSelf: 'flex-end',
    marginBottom: 3,
    marginTop: 10,
    lineHeight: 12,
    textAlignVertical: 'top',
  },
  footermask: {
    width: dimensions.wp(100),
    resizeMode: 'cover',
  },
  infoicon: {
    height: 15,
    width: 15,
    marginHorizontal: 5,
    resizeMode: 'contain',
    tintColor: R.colors.primaryBrand2,
  },
  footermaskSubtext: {
    textDecorationLine: 'underline',
    fontFamily: R.fonts.primaryBold,
    fontSize: 14,
    fontWeight: 'bold',
    lineHeight: 15,
    textAlign: 'left',
    letterSpacing: 0,
    color: R.colors.primaryBrand2,
    top: 2,
  },
  contentContainerBox: {
    // flex: 0.5,
    width: R.dimensions.wp(95),
    alignSelf: 'center',
    alignItems: 'center',
    height: R.dimensions.hp(30),
  },
  flatlistHeaderText: {
    fontSize: horizontalScale(15),
    fontFamily: R.fonts.primaryMedium,
    color: R.themes.backgroundColor,
    padding: 20,
  },
  leftAlignText: {
    backgroundColor: R.themes.boxBackgroundColour,
    flexDirection: 'row',
    flex: 0.21,
    marginVertical: '3%',
    borderTopRightRadius: 30,
    alignItems: 'flex-start',
    padding: '3%',
    marginRight: '10%',
  },
  rightAlignText: {
    backgroundColor: R.themes.boxBackgroundColour,
    flexDirection: 'row',
    flex: 0.21,
    marginVertical: '3%',
    borderTopLeftRadius: 30,
    alignItems: 'flex-end',
    padding: '3%',
    marginLeft: '10%',
    alignItems: 'center',
  },
  nexuslogo: {height: 20, width: 20, resizeMode: 'contain'},
  contentTitle: {
    fontSize: horizontalScale(13),
    fontFamily: R.fonts.primaryRegular,
    color: R.themes.backgroundColor,
    width: '90%',
  },
  linergradientwrapper: {
    alignSelf: 'center',
    borderTopEndRadius: 10,
    borderBottomStartRadius: 10,
    overflow: 'hidden',
  },
  linergradientinner: {
    flex: 1,
    flexDirection: 'row',
    borderTopEndRadius: 10,
    borderBottomStartRadius: 10,
    borderColor: R.themes.boxBackgroundColour,
    paddingVertical: 10,
    borderWidth: 2,
  },

  container: {
    width: '100%',
    justifyContent: 'center',
    position: 'relative',
  },
  baseTrack: {
    //position: 'absolute',
    width: '100%',
    borderRadius: 5,
    height: 5,
  },
  filledTrack: {
    position: 'absolute',
    borderRadius: 5,
  },
});
