import {StyleSheet, Platform} from 'react-native';
//loacl import
import R from '../../../R';

export default StyleSheet.create({
  bstyle: {
    alignSelf: 'center',
    height: R.dimensions.hp('30%'),
    width: R.dimensions.wp('95%'),
    //borderRadius: 30,
    //marginTop: '1%',
  },
  childview: {
    flexDirection: 'row',
    marginVertical: '5%',
    alignItems: 'center',
    marginHorizontal: '5%',
    justifyContent: 'space-between',
  },
  shopImg: {
    alignSelf: 'center',
    backgroundColor: R.themes.backgroundColor,
    height: R.dimensions.hp('7%'),
    width: R.dimensions.wp('18%'),
  },
  nameText: {
    fontSize: R.dimensions.hp('2%'),
    fontFamily: R.fonts.primaryBold,
    alignSelf: 'center',
    color: R.colors.black,
    paddingLeft: 25,
    fontWeight: 'bold',
  },
  mainContainer: {
    marginVertical: '2%',
    marginHorizontal: '3%',
    width: '94%',
    alignSelf: 'center',
    height: R.dimensions.hp('5.5%'),
    borderWidth: 0.5,
    borderColor: R.colors.primaryBrand2,
    flexDirection: 'row',
    // borderRadius: 8,
    justifyContent: 'space-between',
    alignSelf: 'center',
  },
  dotStyle: {
    width: 10,
    height: 10,
    paddingLeft: 10,
    borderRadius: 5,
    backgroundColor: R.colors.darkorange,
  },
  showTime: {
    fontSize: R.dimensions.hp('2.2%'),
    marginHorizontal: '4%',
    fontFamily: R.fonts.primaryRegular,
    paddingBottom: 5,
  },
  bImage: {
    alignSelf: 'center',
    height: R.dimensions.hp('30%'),
    width: R.dimensions.wp('95%'),
  },
  rate: {
    flexDirection: 'row',
    backgroundColor: R.colors.grey,
    padding: 5,
    right: 0,
    borderRadius: 4,
    bottom: 0,
    position: 'absolute',
    width: '12%',
    justifyContent: 'space-around',
    marginRight: '3%',
    marginVertical: '2%',
    height: '8%',
  },
  headerText: {
    //   fontFamily: R.fonts.primaryBold,
    width: R.dimensions.wp(20),
    fontSize: R.dimensions.hp('2%'),
    color: R.colors.black,
  },
  dot: {
    paddingLeft: 35,
    fontSize: R.dimensions.hp('2%'),
    color: R.colors.black,
  },
  headerTime: {
    marginHorizontal: '6%',
    //   fontFamily: R.fonts.primaryBold,
    fontSize: R.dimensions.hp('2%'),
  },
  arrow: {
    marginLeft: '2%',
    height: R.dimensions.hp('3%'),
    width: R.dimensions.wp('5%'),
  },
  timeInnerData: {
    flexDirection: 'row',
    marginHorizontal: '2%',
    marginVertical: '0.2%',
    //  justifyContent: 'space-between',
  },
  endTime: {
    color: R.colors.grey,
    fontSize: R.dimensions.hp('2%'),
    paddingLeft: 5,
  },
  timeContent: {
    textAlign: 'center',
    //fontFamily: R.fonts.primaryRegular,
    color: R.colors.grey,
    fontSize: R.dimensions.hp('2%'),
    paddingLeft: 15,
  },

  day: {
    fontSize: R.dimensions.hp('2%'),
    width: R.dimensions.wp(25),
    //  fontFamily: R.fonts.primaryRegular,
    color: R.colors.grey,
    // height: R.dimensions.hp(3.5),
  },
  headerView: {
    flex: 1,
    flexDirection: 'row',
    //justifyContent: 'space-between',
    alignItems: 'center',
    marginHorizontal: '3%',
    borderBottomColor: R.colors.coolGrey,
    borderBottomWidth: 0.5,
    paddingBottom: 10,
  },
  textStyle: {
    color: R.themes.backgroundColor,
    textAlign: 'left',
    fontFamily: R.fonts.primaryRegular,
    marginTop: R.dimensions.hp(1),
  },
  newtextStyle: {
    color: R.themes.backgroundColor,
    textAlign: 'center',
    fontFamily: R.fonts.primaryRegular,
    marginTop: R.dimensions.hp(7),
    fontWeight: 'bold',
  },

  rateText: {
    fontSize: R.dimensions.hp('1.6%'),
    fontFamily: R.fonts.primaryBold,
    color: R.themes.backgroundColor,
    alignSelf: 'center',
  },
  rateImage: {
    width: R.dimensions.wp('3.5%'),
    height: R.dimensions.hp('2%'),
    alignSelf: 'center',
  },
  locationText: {
    fontSize: R.dimensions.hp('1.8%'),
    color: R.colors.grey,
    alignSelf: 'center',
    marginHorizontal: '2%',
    fontFamily: R.fonts.primaryRegular,
  },
  locationView: {
    marginHorizontal: '3%',
  },
  locationImage: {
    width: R.dimensions.wp('6%'),
    height: R.dimensions.hp('3.2%'),
    marginHorizontal: '2%',
  },
  childView: {
    flexDirection: 'row',
    justifyContent: 'space-around',
  },
  container: {
    marginVertical: '1%',
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginHorizontal: '3%',
    paddingBottom: '1%',
  },
  modelCard: {
    flex: 1,
    backgroundColor: R.colors.lightblack,
    opacity: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  timeView: {
    flexDirection: 'row',
    marginHorizontal: '1%',
    marginVertical: '0.2%',
    borderBottomWidth: 0,
    paddingBottom: 0,
  },
  line: {
    borderWidth: 0.3,
    borderColor: R.colors.gridVioletColour,
    marginHorizontal: '3%',
    marginVertical: '3%',
  },
  cView: {
    width: R.dimensions.wp('20%'),
    marginLeft: 10,
    alignItems: 'center',
  },
  cImage: {
    width: R.dimensions.wp('8.8%'),
    height: R.dimensions.hp('5%'),
    alignSelf: 'center',
  },
  categoryText: {
    fontSize: R.dimensions.hp('2%'),
    textAlign: 'center',
    fontFamily: R.fonts.primaryRegular,
    color: R.colors.grey,
  },
  rootView: {
    height: R.dimensions.wp('16%'),
    width: R.dimensions.wp('16%'),
    //borderRadius: 50,
    // borderColor: R.colors.secondryBrand,
    // borderWidth: 2,
    justifyContent: 'center',
  },
  childViewImage: {
    width: R.dimensions.wp('8%'),
    height: R.dimensions.hp('5%'),
    alignSelf: 'center',
    //marginVertical: '2%',
  },
  childViewText: {
    marginVertical: '2%',
    alignItems: 'center',
    fontSize: R.dimensions.hp('1.9%'),
    color: R.colors.grey,
  },
  cText: {
    fontFamily: R.fonts.primaryBold,
    alignSelf: 'center',
    fontSize: R.dimensions.hp('2.5%'),
  },
  sText: {
    marginVertical: '5%',
    fontSize: R.dimensions.hp('2%'),
    borderBottomColor: R.colors.lightBlueGrey,
    borderBottomWidth: 1,
    padding: 5,
    fontFamily: R.fonts.primaryRegular,
  },
  modalView: {
    backgroundColor: R.themes.backgroundColor,
    padding: 10,
    borderTopLeftRadius: 35,
    borderTopRightRadius: 35,
    elevation: 10,
    alignSelf: 'center',
    flex: 1,
    height: '45%',
    position: 'absolute',
    bottom: 0,
    width: '100%',
  },
  offerImage: {
    height: R.dimensions.hp('25%'),
    width: R.dimensions.wp('100%'),
    backgroundColor: 'red',
    // alignSelf: 'center',
    // marginVertical: '5%',
  },
  text: {
    fontFamily: R.fonts.primaryBold,
    color: R.themes.backgroundColor,
    fontSize: R.dimensions.hp('2.5%'),
  },
  offerText: {
    color: R.themes.backgroundColor,
    fontSize: R.dimensions.hp('2%'),
    marginVertical: '5%',
    fontFamily: R.fonts.primaryRegular,
  },
  view: {
    marginVertical: '5%',
    marginHorizontal: '2%',
  },
  profileImage: {
    height: R.dimensions.hp('5%'),
    width: R.dimensions.wp('10%'),
    borderRadius: 30,
    alignSelf: 'center',
  },
  name: {
    color: R.themes.backgroundColor,
    fontWeight: 'bold',
    fontSize: R.dimensions.hp('2%'),
    fontFamily: R.fonts.primaryBold,
  },
  startImage: {
    height: R.dimensions.hp('3%'),
    width: R.dimensions.wp('5%'),
    marginRight: '2%',
  },
  reviewView: {
    alignSelf: 'center',
    marginVertical: '2%',
  },
  time: {
    color: '#E52070',
    fontSize: R.dimensions.hp('1.8%'),
    fontFamily: R.fonts.primaryBold,
  },
  contactModalView: {
    backgroundColor: R.themes.backgroundColor,
    opacity: 10,
    borderRadius: 15,
    width: R.dimensions.wp('80%'),
    alignItems: 'center',
    height: R.dimensions.hp('20%'),
  },

  leftImage: {
    height: R.dimensions.hp('1.5%'),
    width: R.dimensions.wp('3%'),
  },
  leftContainer: {
    alignSelf: 'flex-end',
    marginVertical: '1.5%',
    marginHorizontal: '3%',
  },
  seaText: {
    fontSize: R.dimensions.h4,
    fontFamily: R.fonts.primaryBold,
    color: R.colors.b,
    padding: 10,
    marginTop: 10,
  },
  subText: {
    color: R.colors.grey,
    fontSize: R.dimensions.hp(1.3),
    width: R.dimensions.wp(50),
    fontFamily: R.fonts.primaryRegular,
  },
  num: {
    fontSize: R.dimensions.h3,
    fontFamily: R.fonts.primaryRegular,
    color: R.colors.black,
    padding: 4,
  },
  cancelBtn: {
    backgroundColor: R.themes.backgroundColor,
    borderWidth: 0.5,
    borderColor: R.themes.boxBackgroundColour,
    borderRadius: 10,
    justifyContent: 'center',
    width: R.dimensions.wp(25),
    height: R.dimensions.hp(4),
    marginHorizontal: '7%',
  },
  callBtn: {
    backgroundColor: R.themes.accountTextColour,
    borderRadius: 10,
    justifyContent: 'center',
    marginHorizontal: '7%',
    width: R.dimensions.wp(25),
    height: R.dimensions.hp(4),
  },
  callText: {
    color: R.themes.backgroundColor,
    fontFamily: R.fonts.primaryBold,
    textAlign: 'center',
  },
  buttonContainer: {
    flexDirection: 'row',

    marginTop: '8%',
  },
  canceltext: {
    fontFamily: R.fonts.primaryBold,
    textAlign: 'center',
    color: R.themes.accountTextColour,
  },
  containerMcard: {
    height: R.dimensions.hp('12%'),
    width: R.dimensions.wp('22%'),
    backgroundColor: R.themes.darkTextColor,
    justifyContent: 'center',
    borderRadius: 5,
    alignSelf: 'center',
    // elevation: 3,

    //borderColor: R.colors.golden,
    borderWidth: 0.5,
    padding: '10%',
    // marginBottom: '10%',
  },
  textMcard: {
    //fontSize: R.dimensions.hp('1.8%'),
    fontSize: R.dimensions.hp(1.28),
    textAlign: 'center',
    top: '8%',
    color: R.themes.lightButtonColor,
    fontFamily: R.fonts.primaryRegular,
    fontWeight: '500',
  },
  imageMcard: {
    width: R.dimensions.wp('7.6%'),
    height: R.dimensions.hp('3.9%'),
    alignSelf: 'center',
  },
});
