import {StyleSheet, Platform} from 'react-native';
//local import
import R from '../../../R';

export default StyleSheet.create({
  text: {
    alignSelf: 'center',
    color: R.colors.black,
  },
  bText: {
    color: R.themes.backgroundColor,
    alignSelf: 'center',
    paddingLeft: 10,
  },
  aboutText: {
    fontSize: R.dimensions.hp('2.2%'),
    fontFamily: R.fonts.primaryBold,
    marginHorizontal: '3%',
    marginVertical: '3%',
  },

  aboutSubText: {
    fontSize: R.dimensions.hp('2%'),
    marginHorizontal: '3%',
    marginVertical: '2%',
    color: R.themes.textInputTextColor,
    letterSpacing: 0.5,
    fontFamily: R.fonts.primaryRegular,
  },
  image: {
    height:
      Platform.OS == 'ios' ? R.dimensions.hp('2.5%') : R.dimensions.hp('2.5%'),
    width: R.dimensions.wp('5%'),
    alignSelf: 'center',
  },
  button: {
    height: R.dimensions.hp('8%'),
    width: R.dimensions.wp('45%'),
    padding: 10,
    backgroundColor: R.colors.darkorange,
    flexDirection: 'row',
    justifyContent: 'space-around',
    borderRadius: 8,
  },
  bottomView: {
    // bottom: 0,
    // position: 'absolute',
    paddingBottom: 20,
    marginVertical: '7%',
    justifyContent: 'space-around',
    alignItems: 'center',
  },
  timeText: {
    fontSize: R.dimensions.hp('2.2%'),
    fontFamily: R.fonts.primaryBold,
    marginHorizontal: '3%',
    marginVertical: '3%',
  },

  view: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginVertical: '4%',
    marginHorizontal: '3%',
  },
  walkImage: {
    width: '20%',
    height: '65%',
    alignSelf: 'center',
    marginLeft: '5%',
  },
  buttonView: {
    marginVertical: '5%',
    width: '40%',
    height: '20%',
    padding: 10,
    backgroundColor: R.themes.backgroundColor,
    flexDirection: 'row',
    borderRadius: 18,
    alignSelf: 'center',
  },
  buttonText: {
    color: R.colors.darkorange,
    alignSelf: 'center',
    paddingLeft: 10,
    fontSize: R.dimensions.hp('2.3%'),
  },
  productName: {
    color: R.themes.backgroundColor,
    fontSize: R.dimensions.hp('2.8%'),
    textAlign: 'center',
  },
  productImage: {
    height: R.dimensions.hp('10%'),
    width: R.dimensions.wp('20%'),
    alignSelf: 'center',
    marginVertical: '4%',
  },
  logoView: {
    height: R.dimensions.hp(14),
    width: R.dimensions.wp(28),
    backgroundColor: R.themes.backgroundColor,
    borderRadius: 55,
    alignSelf: 'center',
    justifyContent: 'center',
    marginVertical: '2%',
  },
  textView: {
    backgroundColor: R.colors.lightblack,
    elevation: 2,
    //  alignSelf: 'center',
    alignSelf: 'center',
    height: R.dimensions.hp('30%'),
    width: R.dimensions.wp('95%'),
    borderRadius: 15,
    justifyContent: 'center',
    //opacity: 0.5,
  },
  name: {
    paddingLeft: 15,
    fontSize: R.dimensions.hp('2%'),
    fontFamily: R.fonts.primaryBold,
    color: R.themes.lightButtonTextColor,
    // alignSelf: 'center',
  },
  value: {
    fontSize: R.dimensions.hp('2%'),
    fontFamily: R.fonts.primaryRegular,
    color: R.themes.lightButtonTextColor,
    paddingLeft: 13,
    alignItems: 'flex-end',
  },
  dotStyle: {
    width: 10,
    height: 10,
    paddingLeft: 10,
    borderRadius: 5,
    backgroundColor: R.colors.darkorange,
  },
  backgroundImage: {
    alignSelf: 'center',
    height: R.dimensions.hp('30%'),
    width: R.dimensions.wp('95%'),
  },
  offerCardView: {
    justifyContent: 'center',
    height: R.dimensions.hp('13%'),
    width: R.dimensions.wp('95%'),
    borderRadius: 5,
    borderColor: R.colors.golden,
    marginBottom: '3%',
    borderWidth: 1,
    alignSelf: 'center',
  },
  offerLogoView: {
    height: R.dimensions.hp('9%'),
    width: R.dimensions.wp('17%'),
    // borderColor: R.colors.golden,
    //borderWidth: 0.5,
    //borderRadius: 30,
    marginLeft: '2%',
    justifyContent: 'center',
  },
  offerLogo: {
    alignSelf: 'center',
    height: R.dimensions.hp('8%'),
    width: R.dimensions.wp('18%'),
  },
  buttonView: {
    height: R.dimensions.hp('8%'),
    width: R.dimensions.wp('80%'),
    alignSelf: 'center',
    borderRadius: 5,
    borderColor: R.colors.golden,
    marginBottom: '3%',
    borderWidth: 0.5,
    justifyContent: 'center',
  },
  img: {
    height: R.dimensions.hp('4%'),
    width: R.dimensions.wp('7%'),
    marginHorizontal: '3%',
  },
  headerView: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: '3%',
    borderBottomColor: R.colors.coolGrey,
    borderBottomWidth: 0.5,
    paddingBottom: 5,
  },
  headerText: {
    fontFamily: R.fonts.primaryRegular,
    width: R.dimensions.wp(20),
    fontSize: R.dimensions.hp('2%'),
    color: R.colors.black,
  },
  dot: {
    paddingLeft: 35,
    fontSize: R.dimensions.hp('2%'),
    color: R.colors.black,
  },
  headerTime: {
    marginHorizontal: '6%',
    fontFamily: R.fonts.primaryRegular,
    fontSize: R.dimensions.hp('2%'),
  },
  arrow: {
    marginLeft: '2%',
    height: R.dimensions.hp('3%'),
    width: R.dimensions.wp('5%'),
  },
  timeInnerData: {
    flexDirection: 'row',
    marginHorizontal: '1%',
    marginVertical: '0.2%',
    //  justifyContent: 'space-between',
  },
  endTime: {
    color: R.colors.grey,
    fontSize: R.dimensions.hp('2%'),
    paddingLeft: 5,
  },
  timeContent: {
    textAlign: 'center',
    fontFamily: R.fonts.primaryRegular,
    color: R.colors.grey,
    fontSize: R.dimensions.hp('2%'),
    paddingLeft: 15,
  },
  day: {
    fontSize: R.dimensions.hp('2%'),
    width: R.dimensions.wp(25),
    fontFamily: R.fonts.primaryRegular,
    color: R.colors.grey,
    // height: R.dimensions.hp(3.5),
  },
  LoginButton: {
    width: R.dimensions.wp(28),
    height: R.dimensions.hp(3.5),
    backgroundColor: R.themes.backgroundColor,
    textAlign: 'center',
    justifyContent: 'center',
    borderRadius: 4,
    borderColor: R.themes.accountTextColour,
    borderWidth: 1,
  },
  LoginButtonText: {
    textAlign: 'center',
    color: R.themes.lightButtonTextColor,

    fontFamily: R.fonts.primaryRegular,
  },
});
